### ISSUE TITLE
Prevent summoning while combat tagged.

### ISSUE THREAD

**Issue by Lazersmoke** [CivClassic/ExilePearl#20]
Same as CivClassic/PrisonPearl#1.

**Comment by Diet-Cola** [comment]
Could this also be extended to combat tagging the prisoner when they are summoned? A lot of legacy issues with summoning was people would never be summoned since they could immediately log out and be re pearled by someone friendly at a later date.

**Comment by Lazersmoke** [comment]
Well we also have logout delays now. Maybe you should just be ep returned on logout? Or we could just [disable summoning entirely](https://github.com/CivClassic/ExilePearl/blob/79eec5d336e756f198eb738d1601ad0300c816ac/src/main/resources/config.yml#L273).

**Comment by Diet-Cola** [comment]
Returning to the end on logout would fix a lot of issues for server that enable it. So long as the prisoner doesn't stay in the overworld long enough to be killed & their pearl stolen.

**Comment by Maxopoly** [comment]
Fixed by https://github.com/CivClassic/ExilePearl/pull/50
