### ISSUE TITLE
You can toss pearls through portals

### ISSUE THREAD

**Issue by GavJenks** [CivClassic/ExilePearl#31]
Including end and nether. Causes multiple problems i those dimensions are restricted on a server

**Comment by GavJenks** [comment]
You can still send pearls through end portals in a chest cart, but not through a nether portal in a chest cart for some reason. So seems okay-ish. I was trying to figure out a way to stuff a pearl in a llama or mule chest, and then send that through the nether portal, but couldn't figure it out. May be a way.

Just simply tossing them is fixed though.

**Comment by Lazersmoke** [comment]
Reopen if you can reproduce in a way that makes the pearl inaccessible.
