### ISSUE TITLE
In some situations, you need to type /ep locate to be freed

### ISSUE THREAD

**Issue by GavJenks** [CivClassic/ExilePearl#34]
Unfortunately I can't seem to nail down exactly the pattern for when this happens in EP, but on the old PP, it used to happen reliably whenever somebody threw your pearl to release it. You would be stuck in the end, even through restarts and logins, until you did /pp locate. So that might lead to finding the problem. Or otherwise, see what code is called on /ep locate, and reconsider whether it should be called more often as well such as on login.

**Comment by Lazersmoke** [comment]
This happens whenever some unhandled thing happens to the pearl. Off the top of my head, I know dropping it on a cactus will cause this. Possible soft-fix is to verify all pearls on restart/during decay task (don't know if this is feasible).

**Comment by GavJenks** [comment]
Can't you verify that person's pearl on login, and on death, personally, too? Maybe also ANY ep command

**Comment by Lazersmoke** [comment]
This issue was moved to DevotedMC/ExilePearl#31
