### ISSUE TITLE
Feature request: /ep broadcast only works on groups, should also work for individuals

### ISSUE THREAD

**Issue by GavJenks** [CivClassic/ExilePearl#35]
This is especially relevant on servers such as civclassic, where there's a low limit on how many namelayer groups you can create (10, there). So if I already created 10 groups, and am pearled, I just can't broadcast easily on my own. I need to go find some poor shmuck to borrow their group or make one for me, which is very awkward. 

PrisonPearl already allowed individual broadcasting, so there should be a coded solution already available from that plugin.

**Comment by Lazersmoke** [comment]
What error message do you get? It should be one of the `Lang.` messages in [here](https://github.com/CivClassic/ExilePearl/blob/master/src/main/java/com/devotedmc/ExilePearl/command/CmdPearlBroadcast.java). The actual strings are [here](https://github.com/CivClassic/ExilePearl/blob/master/src/main/java/com/devotedmc/ExilePearl/Lang.java).

**Comment by GavJenks** [comment]
/ep broadcast gavjenks:  "You don't have permission to chat in that group

**Comment by Lazersmoke** [comment]
It means exactly what it says. You attempted to broadcast into Gavjenk's personal group, but you don't have permission to chat in that group, so you couldn't. Fix is to check for player names if you can't chat in the group. Slightly ugly but informative messages will ensue.

**Comment by GavJenks** [comment]
I indicated "feature request" not "bug" because the error makes perfect sense for groups only. But groups only is jut annoying. It should also let you do individuals, like PP does.

Again the code already exists in PP, and is much more user friendly

**Comment by GavJenks** [comment]
Ohhh did you already merge a fix? If so, cool cool thanks

**Comment by Lazersmoke** [comment]
Individuals are already implemented, it just gave up after finding the group and realizing you couldn't chat in it. Now, it will also check for players. Putting it on the test server now.
