### ISSUE TITLE
Pearls don't affect the pearled unless they're in a tileentity. They should affect while held, too

### ISSUE THREAD

**Issue by GavJenks** [CivClassic/ExilePearl#37]
1) This is strictly a bug, since the instructions text on the config says "The radius around their pearl that an exiled player can't enter" which is definitely false as written.

2)  Even if rewritten, this is a feature we should have. yes, it may be annoying in some cases if a player is repeatedly teleported, but should be a feature anyway, because the plugin also allows for damage mode instead of teleporting, and it's pretty reasonable in that case. Even for teleporting, unless the pearler walks in exactly the direction of the victim, it shouldn't matter often.

Apologies if this is already a feature, but I looked through the config instructions and didn't see mention of it. Just "pearl_radius" alone

**Comment by Lazersmoke** [comment]
@ProgrammerDan
Is there a reason why this exists?
https://github.com/CivClassic/ExilePearl/blob/32907821fefa6bfb3e0d218cf4933e77cbeeaad8/src/main/java/com/devotedmc/ExilePearl/core/PearlBoundaryTask.java#L149-L152
Is there something buggy that can happen or is it just to prevent weirdness like described above where you can get bumped back over and over?

**Comment by Lazersmoke** [comment]
This issue was moved to DevotedMC/ExilePearl#30
