### ISSUE TITLE
Feature Request: In game pearling explanation on first pearling

### ISSUE THREAD

**Issue by crimsonblod** [CivClassic/ExilePearl#58]
Is it possible to provide some in game means to notify the player what being pearled means, offer some common reasons that people are pearled by other players, and some ideas for how to resolve the issue? We could talk to the community for the exact wording, but it seems that a lot of new players who go raiding or something are VERY confused when they are first pearled for whatever reason, and perhaps a reminder on what pearling is the first time they're pearled may be helpful. Either via a different colored text explanation in chat, or some sort of ui, etc...

Thoughts?

**Comment by Maxopoly** [comment]
Sounds good. Needs to be specced out (what should be shown etc.), actually implementing that then is easy and can be done by anyone.

**Comment by Kanyehardbass** [comment]
maybe this can be expanded into a in-game guide which shows such messages when other civ features such as factories, creating/using namelayers, placing bastions are created/interacted with the first time. also maybe be able to be disabled from /config bc i mean not everyone is pearled several days into the server and some people get a better graps at what pearling means before even being pearled.

**Comment by Maxopoly** [comment]
Entirely out of scope for this issue, a related card for a general tutorial plugin exists on our issue tracker.

**Comment by KaloHG** [comment]
I'm willing to make a basic listener for this, however I don't believe ExilePearl has the functionality to record each time a player has been pearled. Adding a basic text message for when a player has been pearled wouldn't be hard at all. However I would like to hear thoughts on this.

**Comment by Maxopoly** [comment]
Just do it every time someone is pearled

**Comment by KaloHG** [comment]
This is the current setup: https://i.imgur.com/ubbC0E8.
recommendations needed.

**Comment by Maxopoly** [comment]
Written entirely in civ lingo and incomprehensible to a newfriend. Also "exert" not "exact".

**Comment by wingzero54** [comment]
Isn't this resolved - pearled players receive a lored stick explaining it to them right?

**Comment by wingzero54** [comment]
Pearled players already receive a lored item with a brief explanation, and I added a link to the wiki with an in-depth explanation of being pearled. I think it's a good way to leverage the wiki knowledge base, and better than adding a more cumbersome explanation with items or books.   https://github.com/CivClassic/AnsibleSetup/pull/128
