### ISSUE TITLE
End spawning issue

### ISSUE THREAD

**Issue by Diet-Cola** [CivClassic/ExilePearl#7]
Still repeatedly spawning at x0, y0, z0, causing the player to fall into the void in an infinite death cycle

**Comment by Diet-Cola** [comment]
New ver: Player spawns at 0,0 still, however the y is sufficient enough that they are spawned on the end island.  

Probably best however to move to randomspawning in the end since spawning players at a singular point is abuse central

**Comment by TealNerd** [comment]
should be fixed

**Comment by Lazersmoke** [comment]
This is fixed by spawning players on the end spawn AKA the end portal endpoint/obby platform that generates when you go through a portal normally.

**Comment by TealNerd** [comment]
It should be spawning at whatever is marked as "world spawn" for the end. might throw in randomspawn to make it a little less easy to trap players
