### ISSUE TITLE
Upgraded players don't immediately get sent to the end

### ISSUE THREAD

**Issue by Inframission** [CivClassic/ExilePearl#77]
Heard a report that after upgrading someone they stuck around in the overworld. It took killing them again to send them to the end.
This may be a concern if exile restrictions get removed for prisoners still in the overworld.

**Comment by wingzero54** [comment]
On the reverse side, downgraded players don't leave the end either

**Comment by wingzero54** [comment]
Tested and upgrading/downgrading works and occurs immediately, @Inframission do you have any additional information?

**Comment by wingzero54** [comment]
As no follow-up was given, going to close this as testing showed players get teleported immediately on upgrade/ downgrade
