### ISSUE TITLE
Items deleted on /ep summon if end chunks are unloaded

### ISSUE THREAD

**Issue by Diet-Cola** [CivClassic/ExilePearl#8]
Steps to repro:

1. Summon a prison pearled player
2. Give items
3. Summon (Notice inventory will be clean)
4. Return (On return, the items will be despawned if no-one is around.)

When a player is in the vicinity of the summoned player, the items will drop and the player will spawn correctly back on top of the items when returned, however if the summoned player is the only person loading the chunks they are in, the items will instantly despawn upon /ep summon

**Comment by TealNerd** [comment]
I can't reproduce this
