### ISSUE TITLE
Logging out with a pearl the server places it in a barrel???

### ISSUE THREAD

**Issue by wingzero54** [CivClassic/ExilePearl#89]
I logged out holding a pearl, logged back in, and there was a barrel floating in the air with the pearl inside of it. Was this some new additional to ExilePearl I'm not aware of? Is it related to me being OP? Is this related to the reports of copies of pearls showing up in barrels around the world?

**Comment by TheOrangeWizard** [comment]
this is intended behaviour that was added at some point

makes it hard to free a pearl without explicitly using /ep free which has certain downsides e.g. a player who is exiled cannot free another pearl at all

**Comment by Diet-Cola** [comment]
Yeah as orange said,

I believe this was introduced in 1.14 update since there was an issue surrounding pearls not freeing in unloaded chunks. To circumvent that Max added this barrel thing

**Comment by wingzero54** [comment]
Ok well this makes a whole lot of sense, I recall hearing reports of pearls appearing in barrels across the map confusing lots of people. I don't think I ever heard it was on purpose for dropped pearls.
